
package vista;

import java.awt.event.ActionListener;

import java.awt.event.WindowAdapter;

import java.awt.event.WindowEvent;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

import javax.swing.DefaultListModel;

import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.text.JTextComponent;

import mensaje.Mensaje;

import usuarios.Destinatario;

public class VistaEmisor extends javax.swing.JFrame implements IVista
{
    private DefaultListModel<Destinatario> modeloDestinatarios;
    private ArrayList<JTextComponent> camposDialog; 
    private ArrayList<JTextComponent> camposMensaje;
    
    public VistaEmisor()
    {
        this.modeloDestinatarios = new DefaultListModel<Destinatario>();
        this.camposDialog = new ArrayList<JTextComponent>();
        this.camposMensaje = new ArrayList<JTextComponent>();
        
        initComponents();
        
        this.BotonEnviar.setActionCommand(IVista.COMANDO_ENVIAR);
        this.BotonEnviar.setEnabled(false);
        
        this.DialogBotonEntrar.setActionCommand(IVista.COMANDO_INICIAR);
        this.DialogBotonEntrar.setEnabled(false);
        
        camposDialog.add(this.DialogTFNombre);
        camposDialog.add(this.DialogTFPuerto);
        
        camposMensaje.add(JTFAsunto);
        camposMensaje.add(JECuerpo);
        
        this.DialogIniciarSesion.addWindowListener(
            new WindowAdapter() 
            { 
                @Override public void windowClosing(WindowEvent e) 
                { 
                    System.exit(0);
                }
            });
        
        this.agregarVerificadorDialog();
        this.agregarVerificadorNuevoMensaje();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents()//GEN-BEGIN:initComponents
    {

        BGTipoMsj = new javax.swing.ButtonGroup();
        DialogIniciarSesion = new javax.swing.JDialog();
        PanelDialogFondo = new javax.swing.JPanel();
        PanelDialog1 = new javax.swing.JPanel();
        PanelDialogJMessenger = new javax.swing.JPanel();
        LabelDialogJMessenger = new javax.swing.JLabel();
        PanelDialog2 = new javax.swing.JPanel();
        PanelDialogNombre = new javax.swing.JPanel();
        LabelDialogNombre = new javax.swing.JLabel();
        PanelDialogTFNombre = new javax.swing.JPanel();
        DialogTFNombre = new javax.swing.JTextField();
        PanelDialog3 = new javax.swing.JPanel();
        PanelDialogPuerto = new javax.swing.JPanel();
        LabelDialogPuerto = new javax.swing.JLabel();
        PanelDialogTFPuerto = new javax.swing.JPanel();
        DialogTFPuerto = new javax.swing.JTextField();
        PanelDialog4 = new javax.swing.JPanel();
        PanelDialogEntrar = new javax.swing.JPanel();
        DialogBotonEntrar = new javax.swing.JButton();
        PanelFondo = new javax.swing.JPanel();
        PanelDestinatarios = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListDestinatarios = new javax.swing.JList<>();
        jPanel4 = new javax.swing.JPanel();
        LabelDestinatarios = new javax.swing.JLabel();
        PanelPrincipal = new javax.swing.JPanel();
        PanelSuperior = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        LabelAsunto = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        LabelJMessenger = new javax.swing.JLabel();
        PanelAsunto = new javax.swing.JPanel();
        JTFAsunto = new javax.swing.JTextField();
        PanelInferior = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTANotificaciones = new javax.swing.JTextArea();
        PanelCentral = new javax.swing.JPanel();
        PanelCentralInferior = new javax.swing.JPanel();
        PanelCentralInferiorIzq = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        PanelTipoMsj = new javax.swing.JPanel();
        JRBSimple = new javax.swing.JRadioButton();
        JRBAviso = new javax.swing.JRadioButton();
        JRBRecepcion = new javax.swing.JRadioButton();
        PanelCentralInferiorDer = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        PanelBotones = new javax.swing.JPanel();
        PanelEnviar = new javax.swing.JPanel();
        BotonCancelar = new javax.swing.JButton();
        PanelCancelar = new javax.swing.JPanel();
        BotonEnviar = new javax.swing.JButton();
        PanelCentralCentral = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        LabelCuerpo = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        PanelCuerpo = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        JECuerpo = new javax.swing.JEditorPane();

        DialogIniciarSesion.setAlwaysOnTop(true);
        DialogIniciarSesion.setModal(true);

        PanelDialogFondo.setBackground(new java.awt.Color(51, 204, 255));
        PanelDialogFondo.setLayout(new java.awt.GridLayout(4, 0));

        PanelDialog1.setBackground(new java.awt.Color(51, 204, 255));
        PanelDialog1.setLayout(new java.awt.GridLayout(1, 3));

        PanelDialogJMessenger.setBackground(new java.awt.Color(51, 204, 255));

        LabelDialogJMessenger.setBackground(new java.awt.Color(51, 204, 255));
        LabelDialogJMessenger.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        LabelDialogJMessenger.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelDialogJMessenger.setText("JMessenger");

        javax.swing.GroupLayout PanelDialogJMessengerLayout = new javax.swing.GroupLayout(PanelDialogJMessenger);
        PanelDialogJMessenger.setLayout(PanelDialogJMessengerLayout);
        PanelDialogJMessengerLayout.setHorizontalGroup(
            PanelDialogJMessengerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelDialogJMessenger, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
        );
        PanelDialogJMessengerLayout.setVerticalGroup(
            PanelDialogJMessengerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelDialogJMessenger, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
        );

        PanelDialog1.add(PanelDialogJMessenger);

        PanelDialogFondo.add(PanelDialog1);

        PanelDialog2.setBackground(new java.awt.Color(51, 204, 255));
        PanelDialog2.setLayout(new java.awt.GridLayout(1, 2));

        PanelDialogNombre.setBackground(new java.awt.Color(51, 204, 255));

        LabelDialogNombre.setBackground(new java.awt.Color(51, 204, 255));
        LabelDialogNombre.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        LabelDialogNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelDialogNombre.setText("Nombre");

        javax.swing.GroupLayout PanelDialogNombreLayout = new javax.swing.GroupLayout(PanelDialogNombre);
        PanelDialogNombre.setLayout(PanelDialogNombreLayout);
        PanelDialogNombreLayout.setHorizontalGroup(
            PanelDialogNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDialogNombreLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(LabelDialogNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        PanelDialogNombreLayout.setVerticalGroup(
            PanelDialogNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelDialogNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
        );

        PanelDialog2.add(PanelDialogNombre);

        PanelDialogTFNombre.setBackground(new java.awt.Color(51, 204, 255));

        DialogTFNombre.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        DialogTFNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DialogTFNombre.setToolTipText("");
        DialogTFNombre.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                DialogTFNombreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelDialogTFNombreLayout = new javax.swing.GroupLayout(PanelDialogTFNombre);
        PanelDialogTFNombre.setLayout(PanelDialogTFNombreLayout);
        PanelDialogTFNombreLayout.setHorizontalGroup(
            PanelDialogTFNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDialogTFNombreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DialogTFNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelDialogTFNombreLayout.setVerticalGroup(
            PanelDialogTFNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDialogTFNombreLayout.createSequentialGroup()
                .addComponent(DialogTFNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelDialog2.add(PanelDialogTFNombre);

        PanelDialogFondo.add(PanelDialog2);

        PanelDialog3.setBackground(new java.awt.Color(51, 204, 255));
        PanelDialog3.setLayout(new java.awt.GridLayout(1, 2));

        PanelDialogPuerto.setBackground(new java.awt.Color(51, 204, 255));

        LabelDialogPuerto.setBackground(new java.awt.Color(51, 204, 255));
        LabelDialogPuerto.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        LabelDialogPuerto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelDialogPuerto.setText("Puerto (0-65535)");

        javax.swing.GroupLayout PanelDialogPuertoLayout = new javax.swing.GroupLayout(PanelDialogPuerto);
        PanelDialogPuerto.setLayout(PanelDialogPuertoLayout);
        PanelDialogPuertoLayout.setHorizontalGroup(
            PanelDialogPuertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelDialogPuerto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
        );
        PanelDialogPuertoLayout.setVerticalGroup(
            PanelDialogPuertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelDialogPuerto, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
        );

        PanelDialog3.add(PanelDialogPuerto);

        PanelDialogTFPuerto.setBackground(new java.awt.Color(51, 204, 255));

        DialogTFPuerto.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        DialogTFPuerto.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout PanelDialogTFPuertoLayout = new javax.swing.GroupLayout(PanelDialogTFPuerto);
        PanelDialogTFPuerto.setLayout(PanelDialogTFPuertoLayout);
        PanelDialogTFPuertoLayout.setHorizontalGroup(
            PanelDialogTFPuertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDialogTFPuertoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DialogTFPuerto, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelDialogTFPuertoLayout.setVerticalGroup(
            PanelDialogTFPuertoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDialogTFPuertoLayout.createSequentialGroup()
                .addComponent(DialogTFPuerto, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelDialog3.add(PanelDialogTFPuerto);

        PanelDialogFondo.add(PanelDialog3);

        PanelDialog4.setBackground(new java.awt.Color(51, 204, 255));
        PanelDialog4.setLayout(new java.awt.GridLayout(1, 3));

        PanelDialogEntrar.setBackground(new java.awt.Color(51, 204, 255));

        DialogBotonEntrar.setBackground(new java.awt.Color(0, 102, 255));
        DialogBotonEntrar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        DialogBotonEntrar.setText("Entrar");
        DialogBotonEntrar.setBorderPainted(false);
        DialogBotonEntrar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                DialogBotonEntrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelDialogEntrarLayout = new javax.swing.GroupLayout(PanelDialogEntrar);
        PanelDialogEntrar.setLayout(PanelDialogEntrarLayout);
        PanelDialogEntrarLayout.setHorizontalGroup(
            PanelDialogEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDialogEntrarLayout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(DialogBotonEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(216, Short.MAX_VALUE))
        );
        PanelDialogEntrarLayout.setVerticalGroup(
            PanelDialogEntrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDialogEntrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DialogBotonEntrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelDialog4.add(PanelDialogEntrar);

        PanelDialogFondo.add(PanelDialog4);

        javax.swing.GroupLayout DialogIniciarSesionLayout = new javax.swing.GroupLayout(DialogIniciarSesion.getContentPane());
        DialogIniciarSesion.getContentPane().setLayout(DialogIniciarSesionLayout);
        DialogIniciarSesionLayout.setHorizontalGroup(
            DialogIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelDialogFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        DialogIniciarSesionLayout.setVerticalGroup(
            DialogIniciarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelDialogFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelFondo.setBackground(new java.awt.Color(51, 204, 255));
        PanelFondo.setLayout(new java.awt.BorderLayout());

        PanelDestinatarios.setBackground(new java.awt.Color(51, 153, 255));
        PanelDestinatarios.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PanelDestinatarios.setPreferredSize(new java.awt.Dimension(300, 798));
        PanelDestinatarios.setLayout(new java.awt.BorderLayout());

        jListDestinatarios.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jListDestinatarios.setModel(this.modeloDestinatarios);
        jListDestinatarios.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jListDestinatarios.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(jListDestinatarios);

        PanelDestinatarios.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel4.setBackground(new java.awt.Color(51, 204, 255));
        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        LabelDestinatarios.setBackground(new java.awt.Color(51, 204, 255));
        LabelDestinatarios.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        LabelDestinatarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelDestinatarios.setText("Destinatarios");
        jPanel4.add(LabelDestinatarios);

        PanelDestinatarios.add(jPanel4, java.awt.BorderLayout.PAGE_START);

        PanelFondo.add(PanelDestinatarios, java.awt.BorderLayout.LINE_START);

        PanelPrincipal.setBackground(new java.awt.Color(51, 153, 255));
        PanelPrincipal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PanelPrincipal.setLayout(new java.awt.BorderLayout());

        PanelSuperior.setBackground(new java.awt.Color(51, 204, 255));
        PanelSuperior.setPreferredSize(new java.awt.Dimension(881, 150));
        PanelSuperior.setLayout(new java.awt.BorderLayout());

        jPanel9.setBackground(new java.awt.Color(51, 204, 255));
        jPanel9.setPreferredSize(new java.awt.Dimension(881, 70));
        jPanel9.setLayout(new java.awt.GridLayout(1, 2));

        jPanel11.setBackground(new java.awt.Color(51, 204, 255));

        LabelAsunto.setBackground(new java.awt.Color(51, 204, 255));
        LabelAsunto.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        LabelAsunto.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelAsunto.setText("Asunto");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelAsunto, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(215, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(LabelAsunto, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel9.add(jPanel11);

        jPanel10.setBackground(new java.awt.Color(51, 204, 255));

        LabelJMessenger.setBackground(new java.awt.Color(51, 204, 255));
        LabelJMessenger.setFont(new java.awt.Font("Tahoma", 2, 30)); // NOI18N
        LabelJMessenger.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        LabelJMessenger.setText("JMessenger  ");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(0, 227, Short.MAX_VALUE)
                .addComponent(LabelJMessenger, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(LabelJMessenger, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jPanel9.add(jPanel10);

        PanelSuperior.add(jPanel9, java.awt.BorderLayout.PAGE_START);

        PanelAsunto.setBackground(new java.awt.Color(51, 204, 255));

        JTFAsunto.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        JTFAsunto.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                JTFAsuntoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelAsuntoLayout = new javax.swing.GroupLayout(PanelAsunto);
        PanelAsunto.setLayout(PanelAsuntoLayout);
        PanelAsuntoLayout.setHorizontalGroup(
            PanelAsuntoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAsuntoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JTFAsunto, javax.swing.GroupLayout.DEFAULT_SIZE, 857, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelAsuntoLayout.setVerticalGroup(
            PanelAsuntoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAsuntoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JTFAsunto, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelSuperior.add(PanelAsunto, java.awt.BorderLayout.CENTER);

        PanelPrincipal.add(PanelSuperior, java.awt.BorderLayout.PAGE_START);

        PanelInferior.setBackground(new java.awt.Color(51, 204, 255));
        PanelInferior.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        PanelInferior.setPreferredSize(new java.awt.Dimension(881, 150));

        JTANotificaciones.setEditable(false);
        JTANotificaciones.setBackground(new java.awt.Color(204, 204, 204));
        JTANotificaciones.setColumns(20);
        JTANotificaciones.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        JTANotificaciones.setRows(5);
        jScrollPane2.setViewportView(JTANotificaciones);

        javax.swing.GroupLayout PanelInferiorLayout = new javax.swing.GroupLayout(PanelInferior);
        PanelInferior.setLayout(PanelInferiorLayout);
        PanelInferiorLayout.setHorizontalGroup(
            PanelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInferiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 853, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelInferiorLayout.setVerticalGroup(
            PanelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInferiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelPrincipal.add(PanelInferior, java.awt.BorderLayout.PAGE_END);

        PanelCentral.setBackground(new java.awt.Color(51, 204, 255));
        PanelCentral.setLayout(new java.awt.BorderLayout());

        PanelCentralInferior.setBackground(new java.awt.Color(51, 204, 255));
        PanelCentralInferior.setMinimumSize(new java.awt.Dimension(100, 300));
        PanelCentralInferior.setPreferredSize(new java.awt.Dimension(881, 150));
        PanelCentralInferior.setLayout(new java.awt.GridLayout(1, 2));

        PanelCentralInferiorIzq.setBackground(new java.awt.Color(51, 204, 255));
        PanelCentralInferiorIzq.setLayout(new java.awt.BorderLayout());

        jPanel20.setBackground(new java.awt.Color(51, 204, 255));
        jPanel20.setPreferredSize(new java.awt.Dimension(20, 150));

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        PanelCentralInferiorIzq.add(jPanel20, java.awt.BorderLayout.LINE_START);

        PanelTipoMsj.setBackground(new java.awt.Color(51, 204, 255));
        PanelTipoMsj.setLayout(new java.awt.GridLayout(3, 0));

        JRBSimple.setBackground(new java.awt.Color(51, 204, 255));
        BGTipoMsj.add(JRBSimple);
        JRBSimple.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JRBSimple.setSelected(true);
        JRBSimple.setText("Simple");
        JRBSimple.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                JRBSimpleActionPerformed(evt);
            }
        });
        PanelTipoMsj.add(JRBSimple);

        JRBAviso.setBackground(new java.awt.Color(51, 204, 255));
        BGTipoMsj.add(JRBAviso);
        JRBAviso.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JRBAviso.setText("Con Aviso");
        JRBAviso.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                JRBAvisoActionPerformed(evt);
            }
        });
        PanelTipoMsj.add(JRBAviso);

        JRBRecepcion.setBackground(new java.awt.Color(51, 204, 255));
        BGTipoMsj.add(JRBRecepcion);
        JRBRecepcion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        JRBRecepcion.setText("Con Recepción");
        PanelTipoMsj.add(JRBRecepcion);

        PanelCentralInferiorIzq.add(PanelTipoMsj, java.awt.BorderLayout.CENTER);

        PanelCentralInferior.add(PanelCentralInferiorIzq);

        PanelCentralInferiorDer.setBackground(new java.awt.Color(51, 204, 255));
        PanelCentralInferiorDer.setLayout(new java.awt.BorderLayout());

        jPanel22.setBackground(new java.awt.Color(51, 204, 255));
        jPanel22.setPreferredSize(new java.awt.Dimension(11, 150));

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        PanelCentralInferiorDer.add(jPanel22, java.awt.BorderLayout.LINE_END);

        jPanel23.setBackground(new java.awt.Color(51, 204, 255));
        jPanel23.setLayout(new java.awt.BorderLayout());

        PanelBotones.setPreferredSize(new java.awt.Dimension(150, 150));
        PanelBotones.setLayout(new java.awt.BorderLayout());

        PanelEnviar.setBackground(new java.awt.Color(51, 204, 255));

        BotonCancelar.setBackground(new java.awt.Color(0, 102, 255));
        BotonCancelar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BotonCancelar.setText("Cancelar");
        BotonCancelar.setBorderPainted(false);
        BotonCancelar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BotonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelEnviarLayout = new javax.swing.GroupLayout(PanelEnviar);
        PanelEnviar.setLayout(PanelEnviarLayout);
        PanelEnviarLayout.setHorizontalGroup(
            PanelEnviarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEnviarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BotonCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelEnviarLayout.setVerticalGroup(
            PanelEnviarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEnviarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BotonCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(61, 61, 61))
        );

        PanelBotones.add(PanelEnviar, java.awt.BorderLayout.PAGE_END);

        PanelCancelar.setBackground(new java.awt.Color(51, 204, 255));

        BotonEnviar.setBackground(new java.awt.Color(0, 102, 255));
        BotonEnviar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BotonEnviar.setText("Enviar");
        BotonEnviar.setBorderPainted(false);
        BotonEnviar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                BotonEnviarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelCancelarLayout = new javax.swing.GroupLayout(PanelCancelar);
        PanelCancelar.setLayout(PanelCancelarLayout);
        PanelCancelarLayout.setHorizontalGroup(
            PanelCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCancelarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BotonEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelCancelarLayout.setVerticalGroup(
            PanelCancelarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCancelarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BotonEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelBotones.add(PanelCancelar, java.awt.BorderLayout.CENTER);

        jPanel23.add(PanelBotones, java.awt.BorderLayout.LINE_END);

        PanelCentralInferiorDer.add(jPanel23, java.awt.BorderLayout.CENTER);

        PanelCentralInferior.add(PanelCentralInferiorDer);

        PanelCentral.add(PanelCentralInferior, java.awt.BorderLayout.PAGE_END);

        PanelCentralCentral.setLayout(new java.awt.BorderLayout());

        jPanel14.setBackground(new java.awt.Color(51, 204, 255));
        jPanel14.setPreferredSize(new java.awt.Dimension(881, 80));
        jPanel14.setLayout(new java.awt.GridLayout(1, 2));

        jPanel17.setBackground(new java.awt.Color(51, 204, 255));

        LabelCuerpo.setBackground(new java.awt.Color(51, 204, 255));
        LabelCuerpo.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        LabelCuerpo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelCuerpo.setText("Cuerpo");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelCuerpo, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(215, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addGap(0, 21, Short.MAX_VALUE)
                .addComponent(LabelCuerpo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel14.add(jPanel17);

        jPanel16.setBackground(new java.awt.Color(51, 204, 255));

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jPanel14.add(jPanel16);

        PanelCentralCentral.add(jPanel14, java.awt.BorderLayout.PAGE_START);

        PanelCuerpo.setBackground(new java.awt.Color(51, 204, 255));

        JECuerpo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jScrollPane3.setViewportView(JECuerpo);

        javax.swing.GroupLayout PanelCuerpoLayout = new javax.swing.GroupLayout(PanelCuerpo);
        PanelCuerpo.setLayout(PanelCuerpoLayout);
        PanelCuerpoLayout.setHorizontalGroup(
            PanelCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCuerpoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 857, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelCuerpoLayout.setVerticalGroup(
            PanelCuerpoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCuerpoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                .addContainerGap())
        );

        PanelCentralCentral.add(PanelCuerpo, java.awt.BorderLayout.CENTER);

        PanelCentral.add(PanelCentralCentral, java.awt.BorderLayout.CENTER);

        PanelPrincipal.add(PanelCentral, java.awt.BorderLayout.CENTER);

        PanelFondo.add(PanelPrincipal, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }//GEN-END:initComponents

    private void JRBSimpleActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_JRBSimpleActionPerformed
    {//GEN-HEADEREND:event_JRBSimpleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JRBSimpleActionPerformed

    private void JRBAvisoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_JRBAvisoActionPerformed
    {//GEN-HEADEREND:event_JRBAvisoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JRBAvisoActionPerformed

    private void JTFAsuntoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_JTFAsuntoActionPerformed
    {//GEN-HEADEREND:event_JTFAsuntoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFAsuntoActionPerformed

    private void BotonCancelarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BotonCancelarActionPerformed
    {//GEN-HEADEREND:event_BotonCancelarActionPerformed
        this.limpiarVista();
    }//GEN-LAST:event_BotonCancelarActionPerformed

    private void DialogBotonEntrarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_DialogBotonEntrarActionPerformed
    {//GEN-HEADEREND:event_DialogBotonEntrarActionPerformed
        this.DialogIniciarSesion.dispose();
    }//GEN-LAST:event_DialogBotonEntrarActionPerformed

    private void DialogTFNombreActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_DialogTFNombreActionPerformed
    {//GEN-HEADEREND:event_DialogTFNombreActionPerformed

    }//GEN-LAST:event_DialogTFNombreActionPerformed

    private void BotonEnviarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_BotonEnviarActionPerformed
    {//GEN-HEADEREND:event_BotonEnviarActionPerformed
        this.limpiarVista();
    }//GEN-LAST:event_BotonEnviarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BGTipoMsj;
    private javax.swing.JButton BotonCancelar;
    private javax.swing.JButton BotonEnviar;
    private javax.swing.JButton DialogBotonEntrar;
    private javax.swing.JDialog DialogIniciarSesion;
    private javax.swing.JTextField DialogTFNombre;
    private javax.swing.JTextField DialogTFPuerto;
    private javax.swing.JEditorPane JECuerpo;
    private javax.swing.JRadioButton JRBAviso;
    private javax.swing.JRadioButton JRBRecepcion;
    private javax.swing.JRadioButton JRBSimple;
    private javax.swing.JTextArea JTANotificaciones;
    private javax.swing.JTextField JTFAsunto;
    private javax.swing.JLabel LabelAsunto;
    private javax.swing.JLabel LabelCuerpo;
    private javax.swing.JLabel LabelDestinatarios;
    private javax.swing.JLabel LabelDialogJMessenger;
    private javax.swing.JLabel LabelDialogNombre;
    private javax.swing.JLabel LabelDialogPuerto;
    private javax.swing.JLabel LabelJMessenger;
    private javax.swing.JPanel PanelAsunto;
    private javax.swing.JPanel PanelBotones;
    private javax.swing.JPanel PanelCancelar;
    private javax.swing.JPanel PanelCentral;
    private javax.swing.JPanel PanelCentralCentral;
    private javax.swing.JPanel PanelCentralInferior;
    private javax.swing.JPanel PanelCentralInferiorDer;
    private javax.swing.JPanel PanelCentralInferiorIzq;
    private javax.swing.JPanel PanelCuerpo;
    private javax.swing.JPanel PanelDestinatarios;
    private javax.swing.JPanel PanelDialog1;
    private javax.swing.JPanel PanelDialog2;
    private javax.swing.JPanel PanelDialog3;
    private javax.swing.JPanel PanelDialog4;
    private javax.swing.JPanel PanelDialogEntrar;
    private javax.swing.JPanel PanelDialogFondo;
    private javax.swing.JPanel PanelDialogJMessenger;
    private javax.swing.JPanel PanelDialogNombre;
    private javax.swing.JPanel PanelDialogPuerto;
    private javax.swing.JPanel PanelDialogTFNombre;
    private javax.swing.JPanel PanelDialogTFPuerto;
    private javax.swing.JPanel PanelEnviar;
    private javax.swing.JPanel PanelFondo;
    private javax.swing.JPanel PanelInferior;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JPanel PanelSuperior;
    private javax.swing.JPanel PanelTipoMsj;
    private javax.swing.JList<Destinatario> jListDestinatarios;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables

    @Override
    public List<Destinatario> getDestinatarios()
    {
        return this.jListDestinatarios.getSelectedValuesList();
    }

    @Override
    public String getAsunto()
    {
        return this.JTFAsunto.getText();
    }

    @Override
    public String getCuerpo()
    {
        return this.JECuerpo.getText();
    }

    @Override
    public int getTipoMensaje()
    {
        int tipo = 0;
        
        if (this.JRBSimple.isSelected())
            tipo = Mensaje.MENSAJE_SIMPLE;
        else if (this.JRBAviso.isSelected())
            tipo = Mensaje.MENSAJE_ALERTA;
        else if (this.JRBRecepcion.isSelected())
            tipo = Mensaje.MENSAJE_RECEPCION;
        
        return tipo;
    }

    @Override
    public String getNombre()
    {
        return this.DialogTFNombre.getText();
    }

    @Override
    public String getPuerto()
    {
        return this.DialogTFPuerto.getText();
    }

    @Override
    public void addActionListener(ActionListener listener)
    {
        this.BotonCancelar.addActionListener(listener);
        this.BotonEnviar.addActionListener(listener);
        this.DialogBotonEntrar.addActionListener(listener);
    }

    @Override
    public void informarEmisor(String mensaje)
    {
        this.JTANotificaciones.append("- " + mensaje + "\n");
        this.repaint();
    }

    @Override
    public void actualizarAgenda(Iterator<Destinatario> destinatarios)
    {
        this.modeloDestinatarios.clear();
        while (destinatarios.hasNext())
            this.modeloDestinatarios.addElement(destinatarios.next());
        this.repaint();
    }

    @Override
    public void setVisible(boolean b)
    {
        super.setVisible(b);
        
        this.DialogIniciarSesion.setSize(614, 340);
        this.DialogIniciarSesion.setVisible(b);
    }
    
    private void limpiarVista()
    {
        this.JTFAsunto.setText("");
        this.JECuerpo.setText("");
        this.jListDestinatarios.clearSelection();
        this.JRBSimple.setSelected(true);
    }
    
    private void agregarVerificadorDialog()
    {
        DocumentListener listenerDialog = new DocumentListener() 
            {
                @Override
                public void removeUpdate(DocumentEvent e) { changedUpdate(e); }
                
                @Override
                public void insertUpdate(DocumentEvent e) { changedUpdate(e); }
        
                @Override
                public void changedUpdate(DocumentEvent e) 
                {
                    boolean habilitar = true;
                    Iterator<JTextComponent> iter = camposDialog.iterator();
                    
                    while (iter.hasNext() && habilitar)                              /* controla campos no vacios */
                        habilitar = !iter.next().getText().matches("^( |    |\n|\r)*$");
                    
                    if (habilitar && DialogTFPuerto.getText().matches("^[0-9]+$"))   /* controla 0 <= puerto <= 65535 */
                        habilitar = Integer.parseInt(DialogTFPuerto.getText()) <= 65535;
                    else
                        habilitar = false;

                    DialogBotonEntrar.setEnabled(habilitar);
                }
            };
        
        Iterator<JTextComponent> iter = this.camposDialog.iterator();
        
        while (iter.hasNext())
            iter.next().getDocument().addDocumentListener(listenerDialog);
    }
    
    private void agregarVerificadorNuevoMensaje()
    {
        ListSelectionListener listListener = new ListSelectionListener()
            {
                @Override
                public void valueChanged(ListSelectionEvent e){ verificarNuevoMensaje(); }
            };
        
        DocumentListener listener = new DocumentListener() 
            {
                @Override
                public void removeUpdate(DocumentEvent e) { changedUpdate(e); }
                
                @Override
                public void insertUpdate(DocumentEvent e) { changedUpdate(e); }
        
                @Override
                public void changedUpdate(DocumentEvent e) { verificarNuevoMensaje(); }
            };
        
        Iterator<JTextComponent> iter = this.camposMensaje.iterator();
        
        while (iter.hasNext())
            iter.next().getDocument().addDocumentListener(listener);
        
        jListDestinatarios.addListSelectionListener(listListener);
    }
    
    private void verificarNuevoMensaje()
    {
        boolean habilitar = true;
        Iterator<JTextComponent> iter = camposMensaje.iterator();
        
        while (iter.hasNext() && habilitar)                    /* controla campos no vacios */
            habilitar = !iter.next().getText().matches("^( |	|\n|\r)*$");

        habilitar &=  !jListDestinatarios.isSelectionEmpty();  /* controla al menos un destinatario seleccionado */                   

        BotonEnviar.setEnabled(habilitar);
    }
}
